apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app-deployment
spec:
  selector:
    matchLabels:
      app: spring-boot-k8s
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
        - name: spring-boot-k8s
          image: javaexpress/shoppingcart:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8070
          resources:
            requests:
              memory: "1Gi" 
              cpu: "1000m"      
            limits:
              memory: "1Gi" 
              cpu: "1000m"      
              
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-k8-svc
spec:
  selector:
    app: spring-boot-k8s
  ports:
    - protocol: "TCP"
      port: 8070 # The port that the service is running on in the cluster
      targetPort: 8070 # The port exposed by the service
  type: NodePort
